# Generated by Django 4.0.1 on 2022-01-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_alter_invoices_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='client_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='client_name',
            field=models.CharField(max_length=50),
        ),
    ]
